[env:bluepill_f103c8]
platform = ststm32@20.0.0
board = bluepill_f103c8
framework = arduino
lib_deps = PlotterLib=symlink://../../../lib/PlotterLib
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
upload_protocol = stlink
monitor_speed = 115200
