[env]
platform = ststm32@20.0.0
framework = stm32cube
lib_deps = PlotterLib=symlink://../../../lib/PlotterLib
upload_protocol = stlink
monitor_speed = 115200

[env:nucleo_f401re]
board = nucleo_f401re

[env:nucleo_f411re]
board = nucleo_f411re

[env:bluepill_f103c8]
board = bluepill_f103c8
