[env:native]
platform = native
lib_deps = KymoCore=symlink://../../lib/KymoCore
build_flags = -Wall -Wextra -Werror -DKYMO_ENABLE_X=1 -DKYMO_ENABLE_Z=1 -DKYMO_ENABLE_TIMESTAMP=1 -DKYMO_ENABLE_DECODER=1
