[env:native]
platform = native
lib_deps = PlotterLib=symlink://../../lib/PlotterLib
build_flags = -Wall -Wextra -Werror -DPLOTTER_ENABLE_X=1 -DPLOTTER_ENABLE_Z=1 -DPLOTTER_ENABLE_TIMESTAMP=1 -DPLOTTER_ENABLE_DECODER=1
